trigger:
  batch: true
  branches:
    include:
      - 'main'

resources:
  repositories:
    - repository: sabana-backend
      type: git
      name: Software-Architecture-Project-3/devops-dev-sabana-backend
      ref: main
      trigger:
        - main
    - repository: devops-pipelines-projects
      type: git
      name: Software-Architecture-Project-3/devops-pipelines-projects
      ref: main

parameters:
  - name: Checkout
    type: string
    default: 'sabana-backend'
  - name: Url
    type: string
    default: 'https://sabana-api-app.icyhill-d563c79a.eastus.azurecontainerapps.io/'
  - name: NameProject
    type: string
    default: 'sabana'
  - name: NameProjectShort
    type: string
    default: 'sabana'
  - name: typevmss
    type: string
    default: 'containerapps'
  - name: Business
    type: string
    default: 'sabana'

stages:
  - template: templates/stages/sonar_cloud_py.yml@devops-pipelines-projects
    parameters:
      Checkout: ${{ parameters.Checkout }}
      NameProject: ${{ parameters.NameProject }}
    
  - template: templates/stages/owasp_Initial_py.yml@devops-pipelines-projects
    parameters:
      Checkout: ${{ parameters.Checkout }}
      Url: ${{ parameters.Url }}
      NameProject: ${{ parameters.NameProject }}
      StageName: 'SecurityScanInit' 

  - template: templates/stages/build_push_backend.yml@devops-pipelines-projects
    parameters:
      Checkout: ${{ parameters.Checkout }}
      NameProject: ${{ parameters.NameProject }}

  #- template: templates/stages/deploy_app_container.yml@devops-pipelines-projects
  #  parameters:
  #    Checkout: ${{ parameters.Checkout }}

  - template: templates/stages/owasp_final.yml@devops-pipelines-projects
    parameters:
      Checkout: ${{ parameters.Checkout }}
      Url: ${{ parameters.Url }}
      NameProject: ${{ parameters.NameProject }}
      StageName: 'SecurityScanFin'