trigger:
  batch: true
  branches:
    include:
      - 'main'

resources:
  repositories:
    - repository: sabana-backend
      type: git
      name: Software-Architecture-Project-3/devops-dev-sabana-backend
      ref: main
      trigger:
        - main
    - repository: devops-pipelines-projects
      type: git
      name: Software-Architecture-Project-3/devops-pipelines-projects
      ref: main

parameters:
  - name: Checkout
    type: string
    default: 'sabana-backend'
  - name: Url
    type: string
    default: 'https://sabana-api-app.icyhill-d563c79a.eastus.azurecontainerapps.io/'
  - name: NameProject
    type: string
    default: 'sabana'
  - name: NameProjectShort
    type: string
    default: 'sabana'
  - name: Business
    type: string
    default: 'sabana'
  - name: AgentPool
    default: 'Default'
  - name: DockerRegistryServiceConnection
    default: 'sabana-docker-hub'
  - name: DockerImageRepository
    default: 'anfedimo/sabana-api'
  - name: ImageTag
    default: 'latest'

stages:
  - template: templates/stages/sonar_cloud_py.yml@devops-pipelines-projects
    parameters:
      Checkout: ${{ parameters.Checkout }}
      NameProject: ${{ parameters.NameProject }}

  - template: templates/stages/owasp_Initial_py.yml@devops-pipelines-projects
    parameters:
      Checkout: ${{ parameters.Checkout }}
      Url: ${{ parameters.Url }}
      NameProject: ${{ parameters.NameProject }}
      StageName: 'SecurityScanInit'

  - template: templates/stages/build_push_backend.yml@devops-pipelines-projects
    parameters:
      AgentPool: ${{ parameters.AgentPool }}
      ImageTag: ${{ parameters.ImageTag }}
      Checkout: ${{ parameters.Checkout }}
      DockerRegistryServiceConnection: ${{ parameters.DockerRegistryServiceConnection }}
      DockerImageRepository: ${{ parameters.DockerImageRepository }}


  - template: templates/stages/owasp_final.yml@devops-pipelines-projects
    parameters:
      Checkout: ${{ parameters.Checkout }}
      Url: ${{ parameters.Url }}
      NameProject: ${{ parameters.NameProject }}